env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
ignorePatterns:
  - node_modules/**
  - dist/**
  - lambda/**
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json
root: true
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true
  '@typescript-eslint/no-unused-vars':
    - warn
    - vars: all
      args: after-used
      ignoreRestSiblings: true
      argsIgnorePattern: ^_
  semi:
    - error
    - never
  '@typescript-eslint/await-thenable':
    - error
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: true
      singleline:
        delimiter: comma
        requireLast: false
  '@typescript-eslint/no-this-alias':
    - error
    - allowDestructuring: true
      allowedNames:
        - self
  # Makes prettier (which is alwways for anon) happier
  space-before-function-paren:
    - error
    - named: never
      anonymous: always
      asyncArrow: always

